In [7]:
import numpy as np
import sys

sys.path.append('C:\\Users\\Mark\\PycharmProjects\\activeIdentificationNstu')

from src.identification_criteria import IdentificationCriteria

In [8]:
theta_1: float = -2
theta_2: float = 0.01

F: np.ndarray = np.array(
    [[-0.8, 1], [theta_1, 0]]
)

Psi: np.ndarray = np.array(
    [[theta_2], [1]]
)

H: np.ndarray = np.array(
    [[1, 0]]
)

R: float = 0.1

In [9]:
ic = IdentificationCriteria(F, Psi, R, H)

In [10]:
ic.get_x_i_k_plus()

array([[ 0.21],
       [-1.  ]])

In [11]:
ic.get_epsilon_k_plus()

array([[0.47092766]])

In [12]:
ic.get_delta()

array([[2.45131938]])

In [13]:
N: int = 30
m: int = 1
n: int = 1
v: int = 1

In [14]:
np.linalg.det(self.R)

NameError: name 'self' is not defined

In [15]:
ic.get_identification_criteria(N, m, n)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional

In [16]:
ic.get_identification_criteria_with_delta(N, m, n)

LinAlgError: 0-dimensional array given. Array must be at least two-dimensional