In [1]:
import numpy as np
import sys
import matplotlib.pyplot as plt

sys.path.append('C:\\Users\\Mark\\PycharmProjects\\activeIdentificationNstu')

from src.identification_criteria_r import IdentificationCriteria

# Константы из дано

In [ ]:
![image.png](attachment:38403003-d5cd-4b77-90ae-febcf843149f.png)

# Неградиентный метод

In [2]:
theta_true: list = [-1, 1]

H: np.ndarray = np.array([1, 0])

R: float = 0.1
N: int = 30

P0 = np.array([[0.1, 0], 
               [0, 0.1]])

In [3]:
ic = IdentificationCriteria(R, H, N, P0)

In [4]:
ic.generate_input_x(theta_true)

[array([[0],
        [0]]),
 array([[2.],
        [2.]]),
 array([[2.4],
        [0. ]]),
 array([[ 0.08],
        [-0.4 ]]),
 array([[1.536],
        [1.92 ]]),
 array([[2.6912],
        [0.464 ]]),
 array([[ 0.31104],
        [-0.6912 ]]),
 array([[1.059968],
        [1.68896 ]]),
 array([[2.8409856],
        [0.940032 ]]),
 array([[ 0.66724352],
        [-0.8409856 ]]),
 array([[0.62521958],
        [1.33275648]]),
 array([[2.83258081],
        [1.37478042]]),
 array([[ 1.10871577],
        [-0.83258081]]),
 array([[0.28044657],
        [0.89128423]]),
 array([[2.66692697],
        [1.71955343]]),
 array([[ 1.58601185],
        [-0.66692697]]),
 array([[0.06426355],
        [0.41398815]]),
 array([[2.36257732],
        [1.93573645]]),
 array([[ 2.0456746 ],
        [-0.36257732]]),
 array([[ 0.00088301],
        [-0.0456746 ]]),
 array([[1.953619  ],
        [1.99911699]]),
 array([[2.4362218],
        [0.046381 ]]),
 array([[ 0.09740357],
        [-0.4362218 ]]),
 array([[1.4858553

In [5]:
observation = ic.generate_output_y(theta_true)


In [6]:
np.round(ic.get_identification_criteria(theta_true, observation), 4)

array([15.031])

In [7]:
np.round(ic.get_non_grad_estimate(theta_true), 4)

array([[-0.9973, -1.0036, -0.99  , -1.0108, -0.996 ],
       [ 0.9723,  1.0244,  0.9808,  1.0654,  0.8922]])

# Градиентный метод

In [8]:
ic.get_grad_identification_criteria(theta_true, observation)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [ ]:
ic.get_grad_estimate(theta_true)

# Графики

In [ ]:
y = ic.generate_output_y(theta_true)
y.shape

In [ ]:
z = ic.get_identification_criteria(theta_true, observation)
z

In [ ]:
plt.plot(y)

In [ ]:
ys = map(ic.y, range(30))
plt.plot(list(ys))

In [ ]:
ic.identification_criteria(theta_true)

In [ ]:
ic.grad_identification_criteria(theta_true, 1)

In [12]:
ic.estimates()

(array([[-1., -1., -1., -1., -1.],
        [ 1.,  1.,  1.,  1.,  1.]]),
 array([[-1.       , -1.       , -1.       , -1.       , -1.       ],
        [ 0.9990332,  0.9990332,  0.9990332,  0.9990332,  0.9990332]]))